services:
  openclaw:
    container_name: openclaw
    image: ghcr.io/openclaw/openclaw:latest
    pull_policy: always
    profiles:
      - ia
    restart: always
    environment:
      - OPENCLAW_DISABLE_BONJOUR=1
    volumes:
      - "${PATH_DATA}/ia/openclaw:/home/node/.openclaw"